# Generated by Django 5.2.1 on 2025-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "tbl_id",
                    models.TextField(blank=True, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("type_of_company", models.TextField(blank=True, null=True)),
                ("eligible_branch", models.TextField(blank=True, null=True)),
                ("type_of_job", models.TextField(blank=True, null=True)),
                ("job_profile", models.TextField(blank=True, null=True)),
                ("job_offer", models.TextField(blank=True, null=True)),
                ("max_package_offered", models.TextField(blank=True, null=True)),
                ("eligible_passouts", models.TextField(blank=True, null=True)),
                ("hr_contact_details", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "company",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CseDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("branch", models.TextField(blank=True, null=True)),
                ("registration", models.TextField(blank=True, null=True)),
                (
                    "gate_rank",
                    models.IntegerField(blank=True, db_column="gate rank", null=True),
                ),
            ],
            options={
                "db_table": "cse_department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.SmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MmeDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("branch", models.TextField(blank=True, null=True)),
                ("registration", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "mme_department",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Placements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("type_of_company", models.TextField(blank=True, null=True)),
                ("eligible_branches", models.TextField(blank=True, null=True)),
                ("type_of_job", models.TextField(blank=True, null=True)),
                ("job_profile", models.TextField(blank=True, null=True)),
                ("job_offer", models.TextField(blank=True, null=True)),
                ("package", models.TextField(blank=True, null=True)),
                ("year", models.TextField(blank=True, null=True)),
                ("rollno", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "placements",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Registrations",
            fields=[
                (
                    "registered_id",
                    models.TextField(blank=True, primary_key=True, serialize=False),
                ),
                ("rollnumber", models.TextField(blank=True, null=True)),
                ("company_id", models.TextField(blank=True, null=True)),
                ("level", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "registrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("roll_no", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("branch", models.TextField(blank=True, null=True)),
                ("registered", models.TextField(blank=True, null=True)),
                ("job_type", models.TextField(blank=True, null=True)),
                ("academic_year", models.TextField(blank=True, null=True)),
                ("password", models.TextField(blank=True, null=True)),
                ("gate_rank", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("mobile", models.TextField(blank=True, null=True)),
                ("cgpa", models.TextField(blank=True, null=True)),
                ("placed", models.TextField(blank=True, null=True)),
                ("backlogs", models.TextField(blank=True, null=True)),
                ("linkedin", models.TextField(blank=True, null=True)),
                ("verified", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "student",
                "managed": False,
            },
        ),
    ]
